"""empty message

Revision ID: 4d5d60c8ae08
Revises: 975266dc31b3
Create Date: 2020-08-22 23:02:20.249329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5d60c8ae08'
down_revision = '975266dc31b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masechta2_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masechta_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_time', sa.Integer(), nullable=True),
    sa.Column('second_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['masechta_id'], ['masechta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masechta3_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masechta_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_time', sa.Integer(), nullable=True),
    sa.Column('second_time', sa.Integer(), nullable=True),
    sa.Column('third_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['masechta_id'], ['masechta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masechta4_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masechta_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_time', sa.Integer(), nullable=True),
    sa.Column('second_time', sa.Integer(), nullable=True),
    sa.Column('third_time', sa.Integer(), nullable=True),
    sa.Column('fourth_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['masechta_id'], ['masechta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masechta5_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masechta_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_time', sa.Integer(), nullable=True),
    sa.Column('second_time', sa.Integer(), nullable=True),
    sa.Column('third_time', sa.Integer(), nullable=True),
    sa.Column('fourth_time', sa.Integer(), nullable=True),
    sa.Column('fifth_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['masechta_id'], ['masechta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masechta6_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masechta_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_time', sa.Integer(), nullable=True),
    sa.Column('second_time', sa.Integer(), nullable=True),
    sa.Column('third_time', sa.Integer(), nullable=True),
    sa.Column('fourth_time', sa.Integer(), nullable=True),
    sa.Column('fifth_time', sa.Integer(), nullable=True),
    sa.Column('sixth_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['masechta_id'], ['masechta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masechta7_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masechta_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_time', sa.Integer(), nullable=True),
    sa.Column('second_time', sa.Integer(), nullable=True),
    sa.Column('third_time', sa.Integer(), nullable=True),
    sa.Column('fourth_time', sa.Integer(), nullable=True),
    sa.Column('fifth_time', sa.Integer(), nullable=True),
    sa.Column('sixth_time', sa.Integer(), nullable=True),
    sa.Column('seventh_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['masechta_id'], ['masechta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masechta7_times')
    op.drop_table('masechta6_times')
    op.drop_table('masechta5_times')
    op.drop_table('masechta4_times')
    op.drop_table('masechta3_times')
    op.drop_table('masechta2_times')
    # ### end Alembic commands ###
