"""empty message

Revision ID: ff6ac0f08358
Revises: 8ad974381427
Create Date: 2020-08-27 15:04:24.808207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6ac0f08358'
down_revision = '8ad974381427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pledge_summary', sa.Column('avergae', sa.INTEGER(), nullable=True))
    op.drop_column('pledge_summary', 'average')
    # ### end Alembic commands ###
